# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy XcodeBot Staging"
    lane :distribute_staging do

      project_path = "#{ENV['XCS_SOURCE_DIR']}/XcodeBot"
      ipa_path = "#{project_path}/output"

      sh "xcrun xcodebuild -exportArchive -archivePath \"#{ENV['XCS_ARCHIVE']}\" -exportPath \"#{ipa_path}\" -DTDKProvisioningProfileExtraSearchPaths=/Library/Developer/XcodeServer/ProvisioningProfiles -exportOptionsPlist \"#{project_path}/ExportOptions.plist\""

      firebase_app_distribution(
          app: "1:841477594869:ios:33dd3fdd3279b95ca76fbc",
          ipa_path: "#{ipa_path}/XcodeBot.ipa",
          testers: "papcoe@gmail.com",
          release_notes: "Lots of amazing new features to test out!"
      )
    end
end
