# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Pre-integration Staging"
  lane :staging_pre_integration do

    #source control
    branch_name = ENV['BRANCH'] || 'develop'
    sh "git checkout -f #{branch_name}"
    git_submodule_update(recursive: true, init: true)

    #config versioning
    project_path = "#{ENV['XCS_SOURCE_DIR']}/XcodeBot"
    config_path = "#{project_path}/Configurations/Staging.xcconfig"
    version_number = ENV['VERSION_NUMBER'] || get_xcconfig_value(path: config_path, name: 'VERSION_NUMBER')
    build_number = Time.now.to_i
    update_xcconfig_value(path: config_path,
                          name: 'VERSION_NUMBER',
                          value: version_number)
    update_xcconfig_value(path: config_path,
                          name: 'BUILD_NUMBER',
                          value: "#{build_number}")
    
  end

  desc "Distribute Staging"
  lane :staging_post_integration do

    project_path = "#{ENV['XCS_SOURCE_DIR']}/XcodeBot"
    ipa_path = "#{project_path}/output"

    sh "xcrun xcodebuild -exportArchive -archivePath \"#{ENV['XCS_ARCHIVE']}\" -exportPath \"#{ipa_path}\" -DTDKProvisioningProfileExtraSearchPaths=/Library/Developer/XcodeServer/ProvisioningProfiles -exportOptionsPlist \"#{project_path}/ExportOptions.plist\""

    release_notes = ENV['RELEASE_NOTES'] || 'unknown'

    firebase_app_distribution(
        app: "1:841477594869:ios:33dd3fdd3279b95ca76fbc",
        ipa_path: "#{ipa_path}/XcodeBot.ipa",
        testers: "papcoe@gmail.com",
        release_notes: "#{release_notes}"
    )
  end

end
